dist: xenial
language: python
python:
- "3.7"
if: type = push
script:
- pip3 install --upgrade setuptools pip
- pip3 install yamllint
- yamllint docassemble/jcc/abilitytopay/data/questions
- npm install bootstrap sass
- npx sass source/style.scss docassemble/jcc/abilitytopay/data/static/style.css
